name: Build release packages
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        
      # Dependencies
      # --------------------------------------
      - name: Install build dependencies
        run: |
          sudo apt install -y debhelper python3 python3.8-minimal python3-pip python3-setuptools gettext build-essential patchelf librsvg2-dev desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace ninja-build meson
      
      # Deb Build
      # --------------------------------------
      - name: Build .deb package
        run: dpkg-buildpackage
      
      # Release packages
      # --------------------------------------        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
          title: ${{ steps.get_version.outputs.VERSION }}
          files: |
            Bottles-*-x86_64.AppImage*
            ../pm.mirko.Twitz*.deb
